version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:v0.22.0
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: ${POSTGRES_PASSWORD}
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      # Change next line if you want to connect to a different JSON-RPC endpoint
      ethereum: 'mainnet:http://host.docker.internal:8545'
      GRAPH_LOG: info

    # extra hosts was added for linux compatibility
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ipfs-volume:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: graph-node
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
  ipfs-volume:
